### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by mamude** [persapiens/jsf-spring-boot-starter-example#30]
Marcelo,

Primeiramente parabéns pelo seu trabalho, sou iniciante e gostaria de esclarecer uma dúvida.
Sempre que altero um arquivo xhtml, o servidor não le minha alteração e sou obrigado a reiniciar a aplicação, é assim mesmo?

Abraços!
Samir

**Comment by persapiens** [comment]
Olá Samir,

Não tenho tido problemas em alterar um xhtml e o servidor "perceber" isso em ambiente de desenvolvimento. Não preciso reiniciar a aplicação.

Tenho depurado as aplicações com NetBeans e Eclipse e tem funcionado.

Inclusive sugiro utilizar o [Live Reload](http://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-livereload) que vem com spring-boot-devtools para atualizar automaticamente a página sem a necessidade de pressionar reload no navegador.

Atenciosamente,
Marcelo

**Comment by persapiens** [comment]
Ah,

Lembre-se de setar também no application.yml o parametro abaixo:

```yml
jsf.PROJECT_STAGE: Development
```

**Comment by mamude** [comment]
Marcelo, 

Por algum motivo não quer funcionar.
Segue meu application.yml, é exatamente o mesmo código desse repositório.

jsf:
  PROJECT_STAGE: Development
  primefaces:
    theme: bootstrap
jsf-spring-boot-starter:
  version: @jsf-spring-boot-starter.version@

Teria alguma sugestão?

Att,
Samir

**Comment by mamude** [comment]
Esqueci de informar que estou utilizando o Intellij IDEA Community.

**Comment by mamude** [comment]
Marcelo, descobri que o problema está na IDE mesmo, pelo Netbeans funciona!

Obrigado de qualquer forma.
